"""CSC110 Fall 2021 Project
This module stores constant variables in our projects.

Instructors said that we can use global constants: https://piazza.com/class/ksovzjrlsye72f?cid=1664

Note: Paths should not end with "/"
"""

"""
File structure:
 
data           - Processed and raw data
├── packed         - Packed data
└── twitter        - Data obtained from Twitter
    ├── user           - Twitter user info data
    │   ├── meta           - Meta-data about the follows-chain downloading progress
    │   ├── processed      - Processed (filtered) user data.
    │   └── users          - Raw user info, each json contains info of one user.
    └── user-tweets    - Tweets data
        ├── processed      - Processed tweets.
        └── user           - Raw tweets, each json contains all tweets from a user.
        
src         - Source codes.
├── report      - Report content generated by report_all() @ visualization.py
├── dist        - Static website root generated by write_html() @ report.py
└── resources   - HTML static resources, some are hand-written and some are imported libraries.
"""
DATA_DIR = '../data'
TWEETS_DIR = f'{DATA_DIR}/twitter/user-tweets'
USER_DIR = f'{DATA_DIR}/twitter/user'
REPORT_DIR = './report'
RES_DIR = './resources'

# Debug mode, or developer mode. This affects two things:
# 1. Whether debug messages are outputted
# 2. Whether the web server regenerates the HTML page for every request
DEBUG = True
